#ploidyNGS_guessPloidy.R

# __author__      = "Diego Mauricio Riano-Pachon & Renato Augusto Correa dos Santos"
# __copyright__   = "Copyright 2016,2017"
# __license__     = "GPL v3.0"
# __maintainer__  = "Diego Mauricio Riano-Pachon"
# __email__       = "diriano@gmail.com"

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


#First argument is the coverage of simulated data files to compare against. Should be one of 15, 25, 50 or 100
#Second argument is the tab file generated by ploidyNGS.py
#The folder ./simulation/data must exist, relative to the location of ploidyNGS.py, and must contain the tab files from simulated data

#Usage: Rscript --vanilla ploidyNGS_guessPloidy.R 100 test_depth100.tab test_depth100.ks-distance.PloidyNGS.tbl

args = commandArgs(trailingOnly=TRUE)
cov=as.numeric(args[1])
data=read.table(args[2])
simDataFiles<-list.files("./simulation/data",pattern = paste("*_",cov,".gz",sep=''))
compDist<-as.data.frame(matrix(data=NA,nrow=length(simDataFiles),ncol=5))
colnames(compDist)<-c("Ploidy","Heteozygosity","Coverage","KS.Distance","KS.P-value")
for (i in 1:length(simDataFiles)){
  #Extract the ploidy level, heterozygosity and coverage from the filename of the reference file (simulated)
  x<-unlist(strsplit(simDataFiles[i],"_"))
  ploidy<-gsub("Ploidy","",x[2])
  heterozygosity<-gsub("Heter","",x[3])
  coverage<-gsub(".gz","",x[4])
  #Read the simulated restuls in file
  simData<-read.table(gzfile(paste("./simulation/data/",simDataFiles[i],sep='')))
  #Compute the Kolmogorov-Smirnov distance between the query distribution and the simulated distribution
  ks.res<-suppressWarnings(ks.test(data[which(data$V3 %in% c('First','Second')),'V4'],simData[which(data$V3 %in% c('First','Second')),'V4']))
  #Store resulting data into a table
  compDist[i,1]<-ploidy
  compDist[i,2]<-heterozygosity
  compDist[i,3]<-coverage
  compDist[i,4]<-ks.res$statistic
  compDist[i,5]<-ks.res$p.value
}
#Compute delta KS, this will help to choose the top coimpativle distributions whitin a range
compDist$deltaKS<-compDist$KS.Distance-min(compDist$KS.Distance)
#Write the table to disk
write.table(compDist[order(compDist$KS.Distance),],file=args[3],row.names = F)